name: Compose Smoke Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_DEFAULT_PLATFORM: linux/amd64
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU (optional)
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker (no-op if not required)
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME || github.actor }}
          password: ${{ secrets.DOCKERHUB_TOKEN || '' }}

      - name: Build and validate compose (no-start, amd64)
        run: |
          # Force amd64-only builds to avoid QEMU/dpkg emulation flakes
          docker compose -f docker-compose.buildx.yml build --pull --progress=plain --platform linux/amd64
          docker compose -f docker-compose.buildx.yml up --no-start
